package t1net

import (
	"testing"
)

func TestReadBits(t *testing.T) {
	// Byte 0xA5 = 10100101 in binary
	// LSB-first reading: bit0=1, bit1=0, bit2=1, bit3=0, bit4=0, bit5=1, bit6=0, bit7=1
	reader := newBitStreamReader([]byte{0xA5})

	// Read 4 bits: should get 0101 = 5 (bits 0-3: 1,0,1,0 -> LSB first = 0101 = 5)
	val, err := reader.ReadBits(4)
	if err != nil {
		t.Fatal(err)
	}
	if val != 5 {
		t.Errorf("ReadBits(4): got %d, want 5", val)
	}

	// Read next 4 bits: should get 1010 = 10 (bits 4-7: 0,1,0,1 -> LSB first = 1010 = 10)
	val, err = reader.ReadBits(4)
	if err != nil {
		t.Fatal(err)
	}
	if val != 10 {
		t.Errorf("ReadBits(4): got %d, want 10", val)
	}
}

func TestReadBitsMultiByte(t *testing.T) {
	// Read 16 bits across two bytes: 0x01, 0x00 -> little-endian uint16 = 1
	reader := newBitStreamReader([]byte{0x01, 0x00})
	val, err := reader.ReadBits(16)
	if err != nil {
		t.Fatal(err)
	}
	if val != 1 {
		t.Errorf("ReadBits(16): got %d, want 1", val)
	}
}

func TestReadBitsOverflow(t *testing.T) {
	reader := newBitStreamReader([]byte{0xFF})
	_, err := reader.ReadBits(9) // Only 8 bits available
	if err == nil {
		t.Fatal("expected error reading past end of buffer")
	}
}

func TestReadUint16(t *testing.T) {
	// 0x01, 0x00 in LSB-first bit reading = uint16(1)
	reader := newBitStreamReader([]byte{0x01, 0x00})
	val, err := reader.ReadUint16()
	if err != nil {
		t.Fatal(err)
	}
	if val != 1 {
		t.Errorf("ReadUint16: got %d, want 1", val)
	}
}

func TestBitsRemaining(t *testing.T) {
	reader := newBitStreamReader([]byte{0xFF, 0xFF})
	if reader.BitsRemaining() != 16 {
		t.Errorf("BitsRemaining: got %d, want 16", reader.BitsRemaining())
	}
	reader.ReadBits(5)
	if reader.BitsRemaining() != 11 {
		t.Errorf("BitsRemaining after read: got %d, want 11", reader.BitsRemaining())
	}
}

func TestReadHuffString(t *testing.T) {
	// "Tribes" encoded with Huffman, generated by Darkstar's WriteHuffString
	data := []byte{0x0d, 0x56, 0xc6, 0xbb, 0x6f}
	reader := newBitStreamReader(data)
	s, err := reader.ReadHuffString()
	if err != nil {
		t.Fatal(err)
	}
	if s != "Tribes" {
		t.Errorf("ReadHuffString: got %q, want %q", s, "Tribes")
	}
}

func TestReadHuffStringEmpty(t *testing.T) {
	// Empty string encoded with Huffman
	data := []byte{0x00, 0x00}
	reader := newBitStreamReader(data)
	s, err := reader.ReadHuffString()
	if err != nil {
		t.Fatal(err)
	}
	if s != "" {
		t.Errorf("ReadHuffString: got %q, want %q", s, "")
	}
}

func TestReadHuffStringMultiple(t *testing.T) {
	// "1.11" encoded with Huffman
	data := []byte{0x09, 0xc4, 0x52, 0x14, 0x01}
	reader := newBitStreamReader(data)
	s, err := reader.ReadHuffString()
	if err != nil {
		t.Fatal(err)
	}
	if s != "1.11" {
		t.Errorf("ReadHuffString: got %q, want %q", s, "1.11")
	}
}

func TestHuffmanTree(t *testing.T) {
	hp := getHuffProcessor()

	// Verify that the tree was built: root node should have non-zero population
	if hp.nodes[0].pop == 0 {
		t.Fatal("root node has zero population")
	}

	// Verify a known leaf: 'e' (index 101) should have the shortest code
	// since it has the highest frequency (2872 + boost)
	eLeaf := hp.leaves['e']
	if eLeaf.numBits == 0 {
		t.Fatal("leaf 'e' has zero numBits")
	}
	// 'e' should have fewer bits than a rare character like 0x80
	rareLeaf := hp.leaves[0x80]
	if eLeaf.numBits >= rareLeaf.numBits {
		t.Errorf("'e' (%d bits) should have fewer bits than 0x80 (%d bits)", eLeaf.numBits, rareLeaf.numBits)
	}
}
